### ISSUE TITLE
Path error in error controller.

### ISSUE THREAD

**Issue by ghost** [popphp/pop-bootstrap#2]
Similarly to the maintenance mode, loading the error.phtml view is also incorrect.

Change the line 41 in **Http\Controller\IndexController**

from
```php
$view = new View(__DIR__ . '/../../view/error.phtml', $response);
```
to
```php
$view = new View(__DIR__ . '/../../../view/error.phtml', $response);
```

**Comment by nicksagona** [comment]
Ok this issue has been patched and pushed live with v4.1.2. Thanks for catching it.
