### ISSUE TITLE
Divide admin side and public side

### ISSUE THREAD

**Issue by ghost** [popphp/pop-bootstrap#3]
Hello, for the application I'm developing I need to divide the private side from public side.

This is my absolute bad solution.

### Step 1 - Routing

In the file **routes/web/http.php** I added the array

```php
 '/admin[/]' => [
     'controller' => 'App\Http\Web\Controller\IndexController',
     'action'     => 'dashboard'
],
```
so as to divide the requests between the `public side` **'[/]'** and  `private side` **'/admin[/]'**.

### Step 2 - Managin the session

In the **Session.php** file I made two changes to look for **/admin** as routing and blocking the **login** view is loaded by default.

- ` Response::redirect('/');` changed in `Response::redirect('/admin');`  (Line 61)
- Comment the last `Response::redirect('/');` and `exit();` (Lines 68 and 69)

```php
    /**
     * Check for the user session
     *
     * @param  Application $application
     * @return void
     * @throws \Pop\Http\Exception
     */
    public static function check(Application $application)
    {
        if ($application->modules['pop-bootstrap']->isWeb()) {
            $acceptHeader = $application->router()->getController()->request()->getHeader('Accept');
            if (stripos($acceptHeader, 'text/html') === false) {
                $controller = new \App\Http\Api\Controller\IndexController(
                    $application, $application->router()->getController()->request(), $application->router()->getController()->response()
                );
                $controller->error(406);
            } else {
                $sess   = $application->services['session'];
                $action = $application->router()->getRouteMatch()->getAction();
               if (self::isAuth($sess) && self::isPublicAction($application->router()->getControllerClass(), $action)) {
                    Response::redirect('/admin');
                    exit();
                } else if (!self::isAuth($sess, false) && !self::isPublicAction($application->router()->getControllerClass(), $action)) {
                    if (isset($sess->user)) {
                        $user = new Model\User();
                        $user->logout($sess, $application->services['cookie']);
                    }
                    //Response::redirect('/login');
                    //exit();
               }
            }
        }
    }
```
### Step 3 - Adding action

In the **App\Http\Web\Controller\IndexController** file I logically added the `dashboard` method and modified the `index` method to reflect the new options.

### Step 4 - Redirect to public side after logout

I also wanted to log out the redirect to the public side, and in the `logout` method I modified the redirect so that points to **'/'** (Line 118).

```php
    /**
     * Logout action method
     *
     * @return void
     */
    public function logout()
    {
        $authUser = new Users\Model\User();
        $authUser->logout(
            $this->application->services['session'],
            $this->application->services['cookie'],
            $this->request->getQuery('revoke')
        );
        $this->redirect('/');
    }
```
### Step 5 - Adjust the path for admin view after login

Finally i modified the redirect of the `login `method so that after logging in to the site it leads to the control panel. (Line 93).

```php
/**
     * Login action method
     *
     * @return void
     */
    public function login()
    {
        $this->prepareView('login.phtml');
        $this->view->title = 'Please Login';
        $this->view->form  = Form\Login::createFromFieldsetConfig(
            $this->application->config()['forms']['App\Http\Web\Form\Login']
        );

        if ($this->request->isPost()) {
            $this->view->form->addFilter('strip_tags')
                 ->addFilter('htmlentities', [ENT_QUOTES, 'UTF-8', false])
                 ->setFieldValues($this->request->getPost());

            $username = $this->view->form->username;
            $password = $this->view->form->password;
            $authUser = new Users\Model\User();
            $result   = $authUser->authenticate($username, $password, $this->application->config['auth_attempts']);

            if ($result == 1) {
                $authUser->login(
                    $this->application->services['session'],
                    $this->application->services['cookie'],
                    $this->application->config()['token_expires']
                );
                $this->redirect('/admin');
            } else {
                $this->view->error = 'Login Failed.';
                if ($result == -1) {
                    $this->view->error .= ' Too Many Attempts.';
                }
            }
        }

        $this->send();
    }
```

I think everything has been done correctly and it works quite well but I have the doubt that we are doing something wrong.

Can you give me your opinion?

**Comment by nicksagona** [comment]
So a couple of things. 1 - the Pop Bootstrap code base really isn't for a CMS with a public and private side. It's really meant for only an admin/private side type of web application. I would make Phire v3 the place to work on the public/private type of CMS applicatin. 2 - I wouldn't necessarily go about it this way. For starters, I wouldn't hard code in a admin URI like `/admin` - I'd make it so the user can make it whatever they want it to be. I wrote a very quick skeleton of what you're trying to over on the v3 branch of Phire CMS. Check that out and see if makes sense. Thanks.

**Comment by nicksagona** [comment]
Specifically, check out the routes here: https://github.com/phirecms/phirecms/blob/v3/app/config/routes/http/web.php and you'll see the constant `APP_URI` which can be prepended to the top of a set of routes to create all of your `/admin/*` routes.

**Comment by nicksagona** [comment]
The constants are defined over here: https://github.com/phirecms/phirecms/blob/v3/app/config/app.config.orig.php

**Comment by ghost** [comment]
I saw the skeleton of v3 and we came more or less to the same conclusions. One difference is that I blocked, through the Event \ Session class, access to the administration pages if the route corresponded to something like **/admin**, **/users**, **/session**, **/roles** etc. and the user does not have the credentials. In this case it is directed to the login. I've also added a set of rules to manage access to control panel pages.

Tomorrow I merge your skeleton with mine and load it on github so that you can take a look and if you like it can be a good starting point for a more complex application as your framework deserves.

**Comment by ghost** [comment]
I tested the cms you wrote but there is always the same problem that if the user is not authenticated you go to the login page. In fact there is no routing that allows you to go to the site (eg: http://www.mysite.it/) and a different one that allows you to go to the control panel (http://www.mysite.it/admin ).

The problem is in the redirect to / login in the Auth class.

I uploaded a version of v3 on my github that makes these distinctions.

It includes but not exhaustively:
- A separate theme for the control panel and one for the site.
- Control panel pages blocked if the user's credentials are not valid (in this case if a url of the type / admin or / users or / session is requested and the user is not registered he / she goes to login while in all other cases access the control panel.

To implement these changes I have also added fields in the database, acl for admin pages, forgot, login and more and many other things.

If you are interested, you can find it here: https://github.com/adrix71/appv3

Username: admin
Password: password

Possibile url:
- http://yoursite/
- http://yoursite/content
- http://yoursite/admin
- http://yoursite/users
- http://yoursite/roles
- http://yoursite/sessions

Test admin, users, roles and sessions with and without valid sessions.

Please note that this version is less than a pre-alpha. Absolutely embryonic and made to try to focus on ideas. It does not claim to be a CMS v3 or another.

**Comment by nicksagona** [comment]
Closing this issue as not related to pop-bootstrap.
