### ISSUE TITLE
Error on Mysql Database

### ISSUE THREAD

**Issue by johnnestebann** [popphp/pop-bootstrap#4]
Hi! I'm serving the framework after a clean instalation, with ./kettle serve, without problems, but when I create the database config like this:

// app/config/database.php

"<?php
return [
    'adapter'  => 'mysql',
    'database' => 'pop',
    'username' => 'root',
    'password' => '',
    'host'     => 'localhost',
    'type'     => ''
];"

It doesn't work, with this error:

"[Tue Oct  1 11:45:42 2019] [::1]:58350 [500]: / - Uncaught Error: Class 'mysqli' not found in /home/user/pop/vendor/popphp/pop-db/src/Adapter/Mysql.php:58
Stack trace:
#0 /home/user/pop/vendor/popphp/pop-db/src/Db.php(146): Pop\Db\Adapter\Mysql->__construct(Array)
#1 /home/user/pop/app/src/Module.php(240): Pop\Db\Db::check('mysql', Array)
#2 /home/user/pop/app/src/Module.php(63): App\Module->initDb(Array)
#3 /home/user/pop/vendor/popphp/popphp/src/Application.php(324): App\Module->register(Object(Popcorn\Pop))
#4 /home/user/pop/public/index.php(10): Pop\Application->register(Object(App\Module))
#5 {main}
  thrown in /home/user/pop/vendor/popphp/pop-db/src/Adapter/Mysql.php on line 58"

Thanks!

**Comment by nicksagona** [comment]
According to the error the MySQLi extension and class isn't installed in your environment. Install that and the error will go away.

**Comment by johnnestebann** [comment]
it was a problem with the mysql socket, sorry and thanks!

**Comment by nicksagona** [comment]
Oh yea - that's a "gotcha" that can happen sometimes. No problem!
