### ISSUE TITLE
Pop Bootstrap 4 dev not work

### ISSUE THREAD

**Issue by ghost** [popphp/pop-bootstrap#5]
First an foremost happy new year Nick.

Second...i tested the bootstrap application version 4-dev but received this error.  For convenience I made the screens.

![1](https://user-images.githubusercontent.com/14064365/71640836-46080700-2c92-11ea-824e-13a5f21a5529.PNG)

![2](https://user-images.githubusercontent.com/14064365/71640837-4accbb00-2c92-11ea-9799-6c3b3d1b6215.PNG)

**Comment by nicksagona** [comment]
Thanks and happy new year to you all well. The latest version of this repo was just released and has been refactored to work with the latest version of the Pop PHP Framework (4.5.0). Also NPM packages have been updated as well. Please use Composer to install/update to the latest version of pop-bootstrap (4.5.0) and also use NPM to install/update those required packages.

**Comment by ghost** [comment]
Hello Nick,
that's exactly what I did. I downloaded the repo and then gave the commands:

`composer install`

`npm install`

`npm run build`

and bum after entering username and password gives me this error. I also tested on Chrome as well as on Firefox but nothing changes.

**Comment by nicksagona** [comment]
Did you configure the database correctly?

**Comment by ghost** [comment]
Yes. I configure the database via composer script...as you designed it

**Comment by nicksagona** [comment]
Unfortunately, I'm unable to duplicate the issue. It's working as it should for me. Both ways as well, via `composer create-project` and within the cloned repo:

`composer create-project popphp/pop-bootstrap project-folder`
(Prompts to configure the database)
`cd project-folder/`
`npm install`
`npm run build`
`./kettle serve`

Same with the cloned repo:

`composer install`
(Prompts to configure the database)
`npm install`
`npm run build`
`./kettle serve`

I was able to log in at the web login screen using admin / password for the credentials.

**Comment by nicksagona** [comment]
![Screenshot_2020-01-01 Please Login](https://user-images.githubusercontent.com/898670/71646905-a9eef780-2cb3-11ea-8a7d-1e4fde05352d.png)

**Comment by nicksagona** [comment]
![Screenshot_2020-01-01 Dashboard](https://user-images.githubusercontent.com/898670/71646906-ad827e80-2cb3-11ea-8a56-ede07f07e1f5.png)

**Comment by ghost** [comment]
The first screen is correct. The second, unfortunately, is not because as soon as I enter my username and password, the errors come out and I don't understand why.

**Comment by nicksagona** [comment]
Sounds like you might have something that wasn't updated correctly. I would recommend deleting your vendor folder and composer.lock file, clearing your composer cache and re-installing with composer.

**Comment by ghost** [comment]
I have cleared the entire project folder, browser cache, composer cache and database.

Then I downloaded the new package from your github and gave the commands again:

`composer install`

`npm install`

`npm run build`

but absolutely nothing changes.

I tested this from another pc where just to do this test I installed a development environment php \ apache \ mysql but gives the same problem.

Lastly, maybe my bad English prevented me from being clear from the beginning, this problem only comes with the `pop-bootstrap-4-dev` version while the others work well.
