### ISSUE TITLE
Future options!

### ISSUE THREAD

**Issue by johnnestebann** [popphp/pop-bootstrap#6]
Hi @nicksagona, are you planning a replacement for the bootstrap version? considering the advancements toward containerization and microservices, I would like to make a "starter kit" using docker and vue, so is there a problem with this or have you another option? Sometimes to get more users we could give them more out-of-box examples, but I don't know if that's your roadmap.
Cheers

**Comment by nicksagona** [comment]
Hey - so this particular repository has been deprecated and is really EOL. But I'm definitely wide open for any new ideas for a "starter kit" / containerization / microservices repo if you want to explore that. Thanks for your interest in Pop PHP!
